### PR TITLE
AutoFills grabber and GetKey method for Yandex Browser

### PR DESCRIPTION
**Pull request by ProrockDev**

### CODE REVIEW

**Comment by MoistCoder** [comment]
Does credit card grabbing work for you? I tested it and it doesn't seem like it works.

**Comment by MoistCoder** [comment]
Also, many comments are wrong and the database parsing code for the collection of credit cards is incorrect:

```cs
creditCards.Add(new Blink.CreditCard()
{
   // Store retrieved information:
   //Id = reader.GetInt32(0),
   Name = reader.GetString(0),
   Month = reader.GetInt32(1),
   Year = reader.GetInt32(2),
   Number = BlinkDecryptor.DecryptValue((byte[])reader[3], key),
}); ;
```

I don't know which browser you picked as an example to orient yourself but chrome has the cc_number stored in the fifth row in the WebData DB. So instead of `(byte[])reader[3]` it would be `(byte[])reader[4]`. I also see a double semicolon and many unnecessary newlines.

**Comment by MoistCoder** [comment]
Some comments are wrong, there are many unnecessary newlines, and I spotted a double semicolon:

```cs
creditCards.Add(new Blink.CreditCard()
{
   // ...
}); ;
```

**Comment by ProrockDev** [comment]
Everything works great for me. I tried in google chrome, opera.
You can moderate the code, I just copied your code under autofills and creditcards to use in my project.

**Pull request merged**
